import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { useState } from "react";
import { Container, Box, Button } from "@mui/material";
import MyButton from "@/components/MyButton";
import Profile from "@/components/Profile";

const inter = Inter({ subsets: ["latin"] });

const player = {
  name: "LeBronJames",
  //avatarUrl: "https://i.imgur.com/2hBebTU.jpeg"
};

export default function Home() {
    const [isConnected, setIsConnected] = useState(false);
    function handleOnClick() {
      setIsConnected(!isConnected);
    }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <Container maxWidth="lg">
            <h1>Bienvenue dans My NBA</h1>
            <Profile player={player} isConnected={isConnected}/>
            <MyButton isConnected={isConnected} handleOnClick={handleOnClick}/>
          </Container>
      </main>
    </>
  );
}
