import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { useContext, useState } from "react";
import { Container, Box, Button, Typography } from "@mui/material";
import MyButton from "@/components/MyButton";
import Profile from "@/components/account/Profile";
import { UserContext } from "@/context/userContext";
import MainNav from "@/components/layout/MainNav";
import Layout from "@/components/layout/Layout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  return (
    <>
      <Head>
        <title>My NBA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Box display={"flex"} flex={1} justifyContent={"center"} alignItems={"center"}>
          <Typography variant="h1">Bienvenue sur My NBA</Typography>
        </Box>
      </Layout>
    </>
  );
}
