import Profile from "@/components/account/Profile";
import Layout from "@/components/layout/Layout";
import { Box, Typography } from "@mui/material";
import Head from "next/head";

export default function Account() {
    

    return (
        <>
        <Head>
            <title>Mon compte</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
            <Box display={"flex"} flex={1} justifyContent={"center"} alignItems={"center"}>
                <Profile />
            </Box>
        </Layout>
        </>
    )
}